#! /bin/bash
postfix="WithFit3HitsTracks"
python3 findSeed.py -l BkgEBeam_SignalHics3000nmOld_BX1_trackInfoClean.txt -s
python3 findSeed.py -l BkgEBeam_SignalHics3000nmOld_BX1_trackInfoClean.txt
python3 findSeed.py -l BkgEBeam_SignalHics3000nmOld_BX2_trackInfoClean.txt -s 
python3 findSeed.py -l BkgEBeam_SignalHics3000nmOld_BX2_trackInfoClean.txt
python3 findSeed.py -l BkgEBeam_SignalHics3000nmOld_BX3_trackInfoClean.txt -s 
python3 findSeed.py -l BkgEBeam_SignalHics3000nmOld_BX3_trackInfoClean.txt
python3 findSeed.py -l BkgEBeam_SignalHics3000nmOld_BX4_trackInfoClean.txt -s 
python3 findSeed.py -l BkgEBeam_SignalHics3000nmOld_BX4_trackInfoClean.txt


python3 findSeed.py -l BkgEBeam_SignalHics5000nmProvisional_BX1_trackInfoClean.txt -s 
python3 findSeed.py -l BkgEBeam_SignalHics5000nmProvisional_BX1_trackInfoClean.txt
python3 findSeed.py -l BkgEBeam_SignalHics5000nmProvisional_BX2_trackInfoClean.txt -s 
python3 findSeed.py -l BkgEBeam_SignalHics5000nmProvisional_BX2_trackInfoClean.txt
python3 findSeed.py -l BkgEBeam_SignalHics5000nmProvisional_BX3_trackInfoClean.txt -s 
python3 findSeed.py -l BkgEBeam_SignalHics5000nmProvisional_BX3_trackInfoClean.txt
python3 findSeed.py -l BkgEBeam_SignalHics5000nmProvisional_BX4_trackInfoClean.txt -s 
python3 findSeed.py -l BkgEBeam_SignalHics5000nmProvisional_BX4_trackInfoClean.txt


mv seedingInformation_BkgEBeam_SignalHics3000nmOld_BX1_trackInfoClean_VariableEnergyCut_OnlySignal_PositronSide.root seedingInformation_BkgEBeam_SignalHics3000nmOld_BX1_trackInfoClean_VariableEnergyCut_OnlySignal_PositronSide_${postfix}.root
mv seedingInformation_BkgEBeam_SignalHics3000nmOld_BX2_trackInfoClean_VariableEnergyCut_OnlySignal_PositronSide.root seedingInformation_BkgEBeam_SignalHics3000nmOld_BX2_trackInfoClean_VariableEnergyCut_OnlySignal_PositronSide_${postfix}.root
mv seedingInformation_BkgEBeam_SignalHics3000nmOld_BX3_trackInfoClean_VariableEnergyCut_OnlySignal_PositronSide.root seedingInformation_BkgEBeam_SignalHics3000nmOld_BX3_trackInfoClean_VariableEnergyCut_OnlySignal_PositronSide_${postfix}.root
mv seedingInformation_BkgEBeam_SignalHics3000nmOld_BX4_trackInfoClean_VariableEnergyCut_OnlySignal_PositronSide.root seedingInformation_BkgEBeam_SignalHics3000nmOld_BX4_trackInfoClean_VariableEnergyCut_OnlySignal_PositronSide_${postfix}.root


mv seedingInformation_BkgEBeam_SignalHics3000nmOld_BX1_trackInfoClean_VariableEnergyCut_SignalAndBackground_PositronSide.root seedingInformation_BkgEBeam_SignalHics3000nmOld_BX1_trackInfoClean_VariableEnergyCut_SignalAndBackground_PositronSide_${postfix}.root
mv seedingInformation_BkgEBeam_SignalHics3000nmOld_BX2_trackInfoClean_VariableEnergyCut_SignalAndBackground_PositronSide.root seedingInformation_BkgEBeam_SignalHics3000nmOld_BX2_trackInfoClean_VariableEnergyCut_SignalAndBackground_PositronSide_${postfix}.root
mv seedingInformation_BkgEBeam_SignalHics3000nmOld_BX3_trackInfoClean_VariableEnergyCut_SignalAndBackground_PositronSide.root seedingInformation_BkgEBeam_SignalHics3000nmOld_BX3_trackInfoClean_VariableEnergyCut_SignalAndBackground_PositronSide_${postfix}.root
mv seedingInformation_BkgEBeam_SignalHics3000nmOld_BX4_trackInfoClean_VariableEnergyCut_SignalAndBackground_PositronSide.root seedingInformation_BkgEBeam_SignalHics3000nmOld_BX4_trackInfoClean_VariableEnergyCut_SignalAndBackground_PositronSide_${postfix}.root



mv seedingInformation_BkgEBeam_SignalHics5000nmProvisional_BX1_trackInfoClean_VariableEnergyCut_OnlySignal_PositronSide.root seedingInformation_BkgEBeam_SignalHics5000nmProvisional_BX1_trackInfoClean_VariableEnergyCut_OnlySignal_PositronSide_${postfix}.root
mv seedingInformation_BkgEBeam_SignalHics5000nmProvisional_BX2_trackInfoClean_VariableEnergyCut_OnlySignal_PositronSide.root seedingInformation_BkgEBeam_SignalHics5000nmProvisional_BX2_trackInfoClean_VariableEnergyCut_OnlySignal_PositronSide_${postfix}.root
mv seedingInformation_BkgEBeam_SignalHics5000nmProvisional_BX3_trackInfoClean_VariableEnergyCut_OnlySignal_PositronSide.root seedingInformation_BkgEBeam_SignalHics5000nmProvisional_BX3_trackInfoClean_VariableEnergyCut_OnlySignal_PositronSide_${postfix}.root
mv seedingInformation_BkgEBeam_SignalHics5000nmProvisional_BX4_trackInfoClean_VariableEnergyCut_OnlySignal_PositronSide.root seedingInformation_BkgEBeam_SignalHics5000nmProvisional_BX4_trackInfoClean_VariableEnergyCut_OnlySignal_PositronSide_${postfix}.root


mv seedingInformation_BkgEBeam_SignalHics5000nmProvisional_BX1_trackInfoClean_VariableEnergyCut_SignalAndBackground_PositronSide.root seedingInformation_BkgEBeam_SignalHics5000nmProvisional_BX1_trackInfoClean_VariableEnergyCut_SignalAndBackground_PositronSide_${postfix}.root
mv seedingInformation_BkgEBeam_SignalHics5000nmProvisional_BX2_trackInfoClean_VariableEnergyCut_SignalAndBackground_PositronSide.root seedingInformation_BkgEBeam_SignalHics5000nmProvisional_BX2_trackInfoClean_VariableEnergyCut_SignalAndBackground_PositronSide_${postfix}.root
mv seedingInformation_BkgEBeam_SignalHics5000nmProvisional_BX3_trackInfoClean_VariableEnergyCut_SignalAndBackground_PositronSide.root seedingInformation_BkgEBeam_SignalHics5000nmProvisional_BX3_trackInfoClean_VariableEnergyCut_SignalAndBackground_PositronSide_${postfix}.root
mv seedingInformation_BkgEBeam_SignalHics5000nmProvisional_BX4_trackInfoClean_VariableEnergyCut_SignalAndBackground_PositronSide.root seedingInformation_BkgEBeam_SignalHics5000nmProvisional_BX4_trackInfoClean_VariableEnergyCut_SignalAndBackground_PositronSide_${postfix}.root

# python plotEnergyPerBX.py
# python plotEnergyPerBX.py -o 
