#! /bin/bash
postfix=""
needFit=""
if [[ $1 == "F" ]]
then
   postfix="WithFit3or4HitsTracksAndDistanceCut"
   needFit=1
else
   postfix="WithoutFit3or4HitsTracksAndDistanceCut"
   needFit=0
fi

echo "!!!!!!#### The postfix to the root file: "${postfix}" and needFit: "${needFit}
signalTracksList="1 5 10 20 30 50 80 100 130 150 170 185 200 220"

for signalTracks in ${signalTracksList}; do
    echo "########## working for nTracks: ${signalTracks} case ############"
    python3 findSeedOld.py -l BkgEBeam_SignalHics3000nmOldForSignalMultiplicityLessThan20Or5000nmForSignalMultiplicityMoreThan20_BX1_SignalTracks${signalTracks}_trackInfoClean.txt -s
    python3 findSeedOld.py -l BkgEBeam_SignalHics3000nmOldForSignalMultiplicityLessThan20Or5000nmForSignalMultiplicityMoreThan20_BX1_SignalTracks${signalTracks}_trackInfoClean.txt
    python3 findSeedOld.py -l BkgEBeam_SignalHics3000nmOldForSignalMultiplicityLessThan20Or5000nmForSignalMultiplicityMoreThan20_BX2_SignalTracks${signalTracks}_trackInfoClean.txt -s 
    python3 findSeedOld.py -l BkgEBeam_SignalHics3000nmOldForSignalMultiplicityLessThan20Or5000nmForSignalMultiplicityMoreThan20_BX2_SignalTracks${signalTracks}_trackInfoClean.txt
    python3 findSeedOld.py -l BkgEBeam_SignalHics3000nmOldForSignalMultiplicityLessThan20Or5000nmForSignalMultiplicityMoreThan20_BX3_SignalTracks${signalTracks}_trackInfoClean.txt -s 
    python3 findSeedOld.py -l BkgEBeam_SignalHics3000nmOldForSignalMultiplicityLessThan20Or5000nmForSignalMultiplicityMoreThan20_BX3_SignalTracks${signalTracks}_trackInfoClean.txt
    python3 findSeedOld.py -l BkgEBeam_SignalHics3000nmOldForSignalMultiplicityLessThan20Or5000nmForSignalMultiplicityMoreThan20_BX4_SignalTracks${signalTracks}_trackInfoClean.txt -s 
    python3 findSeedOld.py -l BkgEBeam_SignalHics3000nmOldForSignalMultiplicityLessThan20Or5000nmForSignalMultiplicityMoreThan20_BX4_SignalTracks${signalTracks}_trackInfoClean.txt




    mv seedingInformation_BkgEBeam_SignalHics3000nmOldForSignalMultiplicityLessThan20Or5000nmForSignalMultiplicityMoreThan20_BX1_SignalTracks${signalTracks}_trackInfoClean_VariableEnergyCut_OnlySignal_PositronSide.root seedingInformation_BkgEBeam_SignalHics3000nmOldForSignalMultiplicityLessThan20Or5000nmForSignalMultiplicityMoreThan20_BX1_SignalTracks${signalTracks}_trackInfoClean_VariableEnergyCut_OnlySignal_PositronSide_${postfix}.root

    mv seedingInformation_BkgEBeam_SignalHics3000nmOldForSignalMultiplicityLessThan20Or5000nmForSignalMultiplicityMoreThan20_BX2_SignalTracks${signalTracks}_trackInfoClean_VariableEnergyCut_OnlySignal_PositronSide.root seedingInformation_BkgEBeam_SignalHics3000nmOldForSignalMultiplicityLessThan20Or5000nmForSignalMultiplicityMoreThan20_BX2_SignalTracks${signalTracks}_trackInfoClean_VariableEnergyCut_OnlySignal_PositronSide_${postfix}.root


    mv seedingInformation_BkgEBeam_SignalHics3000nmOldForSignalMultiplicityLessThan20Or5000nmForSignalMultiplicityMoreThan20_BX3_SignalTracks${signalTracks}_trackInfoClean_VariableEnergyCut_OnlySignal_PositronSide.root seedingInformation_BkgEBeam_SignalHics3000nmOldForSignalMultiplicityLessThan20Or5000nmForSignalMultiplicityMoreThan20_BX3_SignalTracks${signalTracks}_trackInfoClean_VariableEnergyCut_OnlySignal_PositronSide_${postfix}.root

    mv seedingInformation_BkgEBeam_SignalHics3000nmOldForSignalMultiplicityLessThan20Or5000nmForSignalMultiplicityMoreThan20_BX4_SignalTracks${signalTracks}_trackInfoClean_VariableEnergyCut_OnlySignal_PositronSide.root seedingInformation_BkgEBeam_SignalHics3000nmOldForSignalMultiplicityLessThan20Or5000nmForSignalMultiplicityMoreThan20_BX4_SignalTracks${signalTracks}_trackInfoClean_VariableEnergyCut_OnlySignal_PositronSide_${postfix}.root





    mv seedingInformation_BkgEBeam_SignalHics3000nmOldForSignalMultiplicityLessThan20Or5000nmForSignalMultiplicityMoreThan20_BX1_SignalTracks${signalTracks}_trackInfoClean_VariableEnergyCut_SignalAndBackground_PositronSide.root seedingInformation_BkgEBeam_SignalHics3000nmOldForSignalMultiplicityLessThan20Or5000nmForSignalMultiplicityMoreThan20_BX1_SignalTracks${signalTracks}_trackInfoClean_VariableEnergyCut_SignalAndBackground_PositronSide_${postfix}.root

    mv seedingInformation_BkgEBeam_SignalHics3000nmOldForSignalMultiplicityLessThan20Or5000nmForSignalMultiplicityMoreThan20_BX2_SignalTracks${signalTracks}_trackInfoClean_VariableEnergyCut_SignalAndBackground_PositronSide.root seedingInformation_BkgEBeam_SignalHics3000nmOldForSignalMultiplicityLessThan20Or5000nmForSignalMultiplicityMoreThan20_BX2_SignalTracks${signalTracks}_trackInfoClean_VariableEnergyCut_SignalAndBackground_PositronSide_${postfix}.root


    mv seedingInformation_BkgEBeam_SignalHics3000nmOldForSignalMultiplicityLessThan20Or5000nmForSignalMultiplicityMoreThan20_BX3_SignalTracks${signalTracks}_trackInfoClean_VariableEnergyCut_SignalAndBackground_PositronSide.root seedingInformation_BkgEBeam_SignalHics3000nmOldForSignalMultiplicityLessThan20Or5000nmForSignalMultiplicityMoreThan20_BX3_SignalTracks${signalTracks}_trackInfoClean_VariableEnergyCut_SignalAndBackground_PositronSide_${postfix}.root

    mv seedingInformation_BkgEBeam_SignalHics3000nmOldForSignalMultiplicityLessThan20Or5000nmForSignalMultiplicityMoreThan20_BX4_SignalTracks${signalTracks}_trackInfoClean_VariableEnergyCut_SignalAndBackground_PositronSide.root seedingInformation_BkgEBeam_SignalHics3000nmOldForSignalMultiplicityLessThan20Or5000nmForSignalMultiplicityMoreThan20_BX4_SignalTracks${signalTracks}_trackInfoClean_VariableEnergyCut_SignalAndBackground_PositronSide_${postfix}.root
done
